name: flutter_advanced
description: A new Flutter project.
publish_to: 'none'

environment:
  sdk: '>=2.17.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.5
  dio: ^5.1.2
  retrofit: ^4.0.1
  analyzer: ^5.12.0
  json_serializable: ^6.6.2
  json_annotation: ^4.8.1
  dartz: ^0.10.1
  data_connection_checker_nulls: ^0.0.2
  pretty_dio_logger: ^1.3.1
  shared_preferences: ^2.1.1
  device_info_plus: ^9.0.1
  freezed: ^2.3.4
  get_it: ^7.6.0
  lottie: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.3
  retrofit_generator: ^7.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/splash_logo.png
    - assets/images/onboarding_logo1.svg
    - assets/images/onboarding_logo2.svg
    - assets/images/onboarding_logo3.svg
    - assets/images/onboarding_logo4.svg
    - assets/images/hollow_cirlce_ic.svg
    - assets/images/left_arrow_ic.svg
    - assets/images/right_arrow_ic.svg
    - assets/images/solid_circle_ic.svg
    - assets/json/loading.json
    - assets/json/error.json
    - assets/json/empty.json
    - assets/json/success.json
  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Regular.ttf
          weight: 400
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300